services:
  - type: web
    name: st-marys-cathedral-api
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "St Mary's Cathedral"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://church-2m8b.onrender.com
      - key: FRONTEND_URL
        value: https://churchst.netlify.app
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_PERSISTENT
        value: "false"
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_ENCRYPT
        value: "true"
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: ""
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: none
      - key: SESSION_PARTITIONED_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_SCHEME
        value: "null"
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "St Mary's Cathedral"
